# 基本知识点
## 1.范数
* 2-范数，欧式范数，即常见的距离计算公式
* 1-范数，向量各方向的值的和
* 无穷范数，向量各方向中的最大值
## 2.实现

In [1]:
import torch
a=torch.arange(12).reshape(3,-1)
a,a.T

e:\coding_setting\Miniconda\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]]))

## 3.矩阵计算
* 标量分子，向量分母=>结果 <mark>向量与原向量倒置</mark>
* 标量分母，向量分子=>结果 <mark>向量与原向量同类</mark>
* 向量分子，向量分母=>矩阵

In [4]:
x=torch.arange(4.0,requires_grad=True)
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])