# 一、基本操作  
## 1.张量连结

In [60]:
import torch
x=torch.arange(12,dtype=torch.float32).reshape((3,-1))
y=torch.tensor([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
# dim=0按行堆排
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [10., 11., 12., 13.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  5.,  6.,  7.,  8.],
         [ 8.,  9., 10., 11., 10., 11., 12., 13.]]))

## 2.pandas基本操作

### （1）series对象

In [61]:
import pandas as pd
import numpy as np
data1 = np.array(['a','b','c','d'])
data2 = {'a' : 0., 'b' : 1., 'c' : 2.}
data3 = {'a' : 0., 'b' : 1., 'c' : 2.}
s1 = pd.Series(data3,index=['b','c','d','a'])
s2 = pd.Series(data1)
s3 = pd.Series(data2)
s1,s2,s3

(b    1.0
 c    2.0
 d    NaN
 a    0.0
 dtype: float64,
 0    a
 1    b
 2    c
 3    d
 dtype: object,
 a    0.0
 b    1.0
 c    2.0
 dtype: float64)

### (2)dataframe对象

In [62]:
import pandas as pd
data1 = [['Alex',10],['Bob',12],['Clarke',13]]
df1 = pd.DataFrame(data1,columns=['Name','Age'],dtype=float)
data2 = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df2=pd.DataFrame(data2)
data3 = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df3 = pd.DataFrame(data3, index=['first', 'second'])
df1,df2,df3

C:\Users\eric\AppData\Local\Temp\ipykernel_18428\1705438967.py:3: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised.
  df1 = pd.DataFrame(data1,columns=['Name','Age'],dtype=float)


(     Name   Age
 0    Alex  10.0
 1     Bob  12.0
 2  Clarke  13.0,
     Name  Age
 0    Tom   28
 1   Jack   34
 2  Steve   29
 3  Ricky   42,
         a   b     c
 first   1   2   NaN
 second  5  10  20.0)


## 回归


### 1.建立csv文件

In [63]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)#创建文件夹
data_file = os.path.join('..', 'data', 'house_tiny.csv')#创建文件
with open(data_file, 'w') as f:#with:异常处理关键字
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

### 2.读取csv文件
#### (1)函数解析：
* loc,iloc函数

| 方法名称 | 说明 |
| ---      |---|
| .loc[] | 基于标签索引 |
| .iloc[] | 基于整数索引 |

<mark>loc操作时左右都是闭合数</mark>

<mark>iloc操作时前闭后开</mark>

In [64]:
import numpy as np
import pandas as pd
#创建一组数据
data = {'name': ['John', 'Mike', 'Mozla', 'Rose', 'David', 'Marry', 'Wansi', 'Sidy', 'Jack', 'Alic'],

        'age': [20, 32, 29, np.nan, 15, 28, 21, 30, 37, 25],

        'gender': [0, 0, 1, 1, 0, 1, 0, 0, 1, 1],

        'isMarried': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

label = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(data, index=label)
print(df)
#对行操作，左行右列
print(df.loc['a':'d',:]) #等同于df.loc['a':'d']
#对列操作
print(df.loc[:,'name':'gender'])
print(df.iloc[2:4])

    name   age  gender isMarried
a   John  20.0       0       yes
b   Mike  32.0       0       yes
c  Mozla  29.0       1        no
d   Rose   NaN       1       yes
e  David  15.0       0        no
f  Marry  28.0       1        no
g  Wansi  21.0       0        no
h   Sidy  30.0       0       yes
i   Jack  37.0       1        no
j   Alic  25.0       1        no
    name   age  gender isMarried
a   John  20.0       0       yes
b   Mike  32.0       0       yes
c  Mozla  29.0       1        no
d   Rose   NaN       1       yes
    name   age  gender
a   John  20.0       0
b   Mike  32.0       0
c  Mozla  29.0       1
d   Rose   NaN       1
e  David  15.0       0
f  Marry  28.0       1
g  Wansi  21.0       0
h   Sidy  30.0       0
i   Jack  37.0       1
j   Alic  25.0       1
    name   age  gender isMarried
c  Mozla  29.0       1        no
d   Rose   NaN       1       yes


In [65]:
import pandas as pd

data = pd.read_csv(data_file)
inputs1, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs1 = inputs1.fillna(inputs1.mean())#将NAN空值处理成平均值
#get_dummies用来处理缺省元素
inputs2 = pd.get_dummies(inputs1, dummy_na=True)
inputs2

C:\Users\eric\AppData\Local\Temp\ipykernel_18428\1801754754.py:5: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs1 = inputs1.fillna(inputs1.mean())#将NAN空值处理成平均值


NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [66]:
outputs

0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64

张量化

In [67]:
import torch
X, y = torch.tensor(inputs2.values), torch.tensor(outputs.values)
X, y


(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

### 3.数据预处理总结
* 读取csv文件
* 处理缺省值
* 将数据集分块为输入输出
* 将数据值处理为torch张量形式

In [7]:
import torch
x=torch.arange(20).reshape(4,-1)
y=[1,3]
x[y]

tensor([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]])

In [2]:
import torch
a =torch.tensor([[1,2],[3,4],[5,6]])
a.item

OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "e:\coding_setting\Miniconda\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.